# Ejercicio

Construir un *programa* en **Python** que verifique que el siguiente determinante se puede calcular mediante la definición del **Determinante de Vandermonde**, comparando el cálculo a través de la formula; y mediante el módulo **np.linalg.det**

$$\begin{vmatrix}1 & 1 & 1 & 1 & 1\\
1 & 2 & 4 & 8 & 16\\
1 & 3 & 9 & 27 & 81\\
1 & 4 & 16 & 64 & 256\\
1 & 5 & 25 & 125 & 625
\end{vmatrix}$$

In [1]:
# Importar las librerias necesarias
import numpy as np

In [2]:
# Definir la matriz
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 2, 4, 8, 16],
    [1, 3, 9, 27, 81],
    [1, 4, 16, 64, 256],
    [1, 5, 25, 125, 625]
])

# Imprimir la matriz
print("Matriz a Cacular el Determinante: \n", A)

# Mostrar la forma de la matriz
print("Tamaño de la Matriz: ", np.shape(A))

# Calcular y Mostrar el Determinante con Numpy
detA = np.linalg.det(A)
print("Determinante por Numpy: ", detA)

# Calcular el Determinante Mediante la Productoria
x = [1, 2, 3, 4, 5]
detA_ = 1           # Se inicia el valor del determinante en 1
n = np.shape(A)[0]  # Se obtiene la dimensión de la matriz

# Se crea el ciclo para las productorias anidadas
for i in range(0, n):
    for j in range(i, n):

        # Calcular la productoria
        if i!=j:
            detA_ = detA_*(x[i]-x[j])

# Mostrar el determinante mediante la productoria
print("Determinante por Productoria: ", detA_)


Matriz a Cacular el Determinante: 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
Tamaño de la Matriz:  (5, 5)
Determinante por Numpy:  287.9999999999998
Determinante por Productoria:  288
